<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'vendor_id' => 1,
                'category_id' => 2,
                'brand_id' => 1,
                'name' => 'Samsung Galaxy S23',
                'slug' => 'samsung-galaxy-s23',
                'short_description' => 'Latest Samsung flagship phone with 128GB storage',
                'description' => 'Experience the power of Galaxy S23 with amazing camera and battery life. 6.1-inch Dynamic AMOLED display, 50MP main camera, 8K video recording.',
                'sku' => 'SAMS23-001',
                'price' => 79999.00,
                'discount_price' => 74999.00,
                'cost_price' => 65000.00,
                'stock' => 50,
                'weight' => 0.17,
                'length' => 15.0,
                'width' => 7.0,
                'height' => 0.8,
                'status' => 1,
                'is_featured' => 1,
                'is_approved' => 1,
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vendor_id' => 1,
                'category_id' => 2,
                'brand_id' => 2,
                'name' => 'iPhone 14',
                'slug' => 'iphone-14',
                'short_description' => 'Apple iPhone 14 with A15 Bionic chip',
                'description' => 'iPhone 14 features a beautiful 6.1-inch Super Retina XDR display, advanced camera system for stunning photos, and all-day battery life.',
                'sku' => 'IP14-001',
                'price' => 79999.00,
                'discount_price' => 77999.00,
                'cost_price' => 70000.00,
                'stock' => 30,
                'weight' => 0.17,
                'length' => 14.0,
                'width' => 7.0,
                'height' => 0.7,
                'status' => 1,
                'is_featured' => 1,
                'is_approved' => 1,
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vendor_id' => 1,
                'category_id' => 4,
                'brand_id' => 5,
                'name' => 'Sony WH-1000XM4',
                'slug' => 'sony-wh1000xm4',
                'short_description' => 'Industry leading noise canceling headphones',
                'description' => 'Experience exceptional sound quality with Sony\'s industry-leading noise cancellation. 30-hour battery life, touch sensor controls, and speak-to-chat technology.',
                'sku' => 'SNY-HP001',
                'price' => 29990.00,
                'discount_price' => 27990.00,
                'cost_price' => 22000.00,
                'stock' => 40,
                'weight' => 0.25,
                'length' => 20.0,
                'width' => 15.0,
                'height' => 5.0,
                'status' => 1,
                'is_featured' => 1,
                'is_approved' => 1,
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vendor_id' => 2,
                'category_id' => 6,
                'brand_id' => 3,
                'name' => 'Nike Air Max',
                'slug' => 'nike-air-max',
                'short_description' => 'Comfortable running shoes with Air cushioning',
                'description' => 'Nike Air Max provides responsive cushioning and a stylish look. Perfect for running and casual wear.',
                'sku' => 'NAM-001',
                'price' => 5999.00,
                'discount_price' => 5499.00,
                'cost_price' => 4000.00,
                'stock' => 100,
                'weight' => 0.30,
                'length' => 30.0,
                'width' => 20.0,
                'height' => 10.0,
                'status' => 1,
                'is_featured' => 1,
                'is_approved' => 1,
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vendor_id' => 2,
                'category_id' => 7,
                'brand_id' => 4,
                'name' => 'Zara Summer Dress',
                'slug' => 'zara-summer-dress',
                'short_description' => 'Stylish floral print summer dress',
                'description' => 'Lightweight and comfortable summer dress with beautiful floral pattern. Perfect for casual outings and beach days.',
                'sku' => 'ZSD-001',
                'price' => 2999.00,
                'discount_price' => 2499.00,
                'cost_price' => 1500.00,
                'stock' => 75,
                'weight' => 0.20,
                'length' => 25.0,
                'width' => 20.0,
                'height' => 2.0,
                'status' => 1,
                'is_featured' => 1,
                'is_approved' => 1,
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'vendor_id' => 2,
                'category_id' => 8,
                'brand_id' => 6,
                'name' => 'Adidas Ultraboost',
                'slug' => 'adidas-ultraboost',
                'short_description' => 'Premium running shoes with Boost technology',
                'description' => 'Experience ultimate comfort with Adidas Ultraboost. Energy-returning Boost midsole and breathable Primeknit upper.',
                'sku' => 'AD-UB001',
                'price' => 12999.00,
                'discount_price' => 11999.00,
                'cost_price' => 9000.00,
                'stock' => 60,
                'weight' => 0.35,
                'length' => 32.0,
                'width' => 22.0,
                'height' => 11.0,
                'status' => 1,
                'is_featured' => 0,
                'is_approved' => 1,
                'approved_by' => 1,
                'approved_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}